server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Proxy vers le backend (retire le préfixe /api)
    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Vue Router — fallback sur index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
